version: '3.9'
services:
    php-apache:
      container_name: php_chathink
      build: .
      depends_on:
        - mysql
      ports:
        - 8080:80
      volumes:
        - ./src:/var/www/html
      networks:
        - network

    mysql:
      container_name: mysql_chathink
      image: mysql:5.7
      ports:
        - 3306:3306
      volumes:
        - mysql_chathink:/var/lib/mysql
        - ./users.sql:/docker-entrypoint-initdb.d/users.sql # Archivo para inicializar la creacion de las tablas y base de datos
      environment:
        MYSQL_DATABASE: database
        MYSQL_USER: admin
        MYSQL_PASSWORD: admin
        MYSQL_ROOT_PASSWORD: root
      networks:
        - network

networks:
  network:
    driver: bridge

volumes:
  mysql_chathink: